"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_screen from './home-screen.bones.json'
import _schedule_screen from './schedule-screen.bones.json'

registerBones({
  "home-screen": _home_screen,
  "schedule-screen": _schedule_screen,
})
